version: "3"
volumes:
  db:
services:
  mariadb:
    image: mariadb:5.5.62-trusty
    container_name: mariadb
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password
      - MYSQL_DATABASE=your_application_database
      - MYSQL_USER=your_application_user
      - MYSQL_PASSWORD=your_application_password
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    restart: always
    ports:
      - 3306:3306

  flask:
    image: cqunews/newmedia:1.0-min
    container_name: flask
    links:
      - mariadb
    ports:
      - 5000:5000
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8.5
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=your_root_password
    links:
      - mariadb
    ports:
      - 8080:80
